"""
Portfolio allocation donut chart component.

This module renders a professional interactive Plotly donut chart using
allocation data prepared by PortfolioAllocationService.

No portfolio data loading or allocation calculation occurs here.
"""

from __future__ import annotations

import plotly.graph_objects as go
import streamlit as st

from services.analytics.allocation import PortfolioAllocation


CHART_KEY = "analytics_portfolio_allocation_donut"


def _format_currency(value: float) -> str:
    """
    Format a numeric value as Indian rupee currency.

    Args:
        value:
            Currency amount.

    Returns:
        Formatted rupee value.
    """
    return f"₹{value:,.2f}"


def render_allocation_donut(
    allocation: PortfolioAllocation,
) -> None:
    """
    Render the portfolio allocation donut chart.

    Args:
        allocation:
            Portfolio allocation result generated by
            PortfolioAllocationService.
    """
    st.subheader("🍩 Portfolio Allocation")

    st.caption(
        "Distribution of the current portfolio value across mutual funds."
    )

    if not isinstance(allocation, PortfolioAllocation):
        st.error(
            "Portfolio allocation chart requires a valid "
            "PortfolioAllocation object."
        )
        return

    if not allocation.funds:
        st.info(
            "No allocation data is available for visualization."
        )
        return

    fund_names = [
        fund.fund
        for fund in allocation.funds
    ]

    current_values = [
        fund.current_value
        for fund in allocation.funds
    ]

    allocation_percentages = [
        fund.allocation_percentage
        for fund in allocation.funds
    ]

    custom_data = [
        [
            _format_currency(fund.current_value),
            fund.allocation_percentage,
        ]
        for fund in allocation.funds
    ]

    figure = go.Figure(
        data=[
            go.Pie(
                labels=fund_names,
                values=current_values,
                hole=0.62,
                sort=False,
                direction="clockwise",
                customdata=custom_data,
                textinfo="percent",
                textposition="inside",
                insidetextorientation="horizontal",
                hovertemplate=(
                    "<b>%{label}</b><br>"
                    "Current Value: %{customdata[0]}<br>"
                    "Portfolio Weight: %{customdata[1]:.2f}%"
                    "<extra></extra>"
                ),
            )
        ]
    )

    figure.update_layout(
        height=500,
        margin={
            "l": 20,
            "r": 20,
            "t": 30,
            "b": 30,
        },
        showlegend=True,
        legend={
            "orientation": "v",
            "yanchor": "middle",
            "y": 0.5,
            "xanchor": "left",
            "x": 1.02,
            "font": {
                "size": 11,
            },
        },
        annotations=[
            {
                "text": (
                    "<b>Total Value</b><br>"
                    f"{_format_currency(allocation.total_value)}"
                ),
                "x": 0.5,
                "y": 0.5,
                "font": {
                    "size": 15,
                },
                "showarrow": False,
                "align": "center",
            }
        ],
    )

    figure.update_traces(
        marker={
            "line": {
                "color": "white",
                "width": 2,
            }
        },
    )

    st.plotly_chart(
        figure,
        width="stretch",
        config={
            "displayModeBar": False,
            "responsive": True,
        },
        key=CHART_KEY,
    )

    with st.expander("View allocation details"):
        for fund in allocation.funds:
            st.write(
                f"**{fund.fund}** — "
                f"{_format_currency(fund.current_value)} "
                f"({fund.allocation_percentage:.2f}%)"
            )