"""
Gain Distribution Chart

Displays portfolio gains/losses by mutual fund using Plotly.

This component is presentation-only and expects the portfolio
DataFrame generated by PortfolioService.
"""

from __future__ import annotations

import pandas as pd
import plotly.express as px
import streamlit as st


REQUIRED_COLUMNS = (
    "Fund",
    "Profit/Loss",
    "Investment",
    "Current Value",
    "Return %",
)


def render_gain_distribution(df: pd.DataFrame) -> None:
    """
    Render the portfolio gain distribution chart.

    Parameters
    ----------
    df : pd.DataFrame
        Portfolio dataframe.
    """

    st.subheader("📈 Gain Distribution")

    st.caption(
        "Profit/Loss contribution of each mutual fund."
    )

    if df.empty:
        st.info("No portfolio data available.")
        return

    missing = [c for c in REQUIRED_COLUMNS if c not in df.columns]

    if missing:
        st.error(
            f"Missing required columns: {', '.join(missing)}"
        )
        return

    chart_df = df.copy()

    chart_df["Profit/Loss"] = pd.to_numeric(
        chart_df["Profit/Loss"],
        errors="coerce"
    )

    chart_df = chart_df.sort_values(
        by="Profit/Loss",
        ascending=True
    )

    chart_df["Color"] = chart_df["Profit/Loss"].apply(
        lambda x: "Profit" if x >= 0 else "Loss"
    )

    fig = px.bar(
        chart_df,
        x="Profit/Loss",
        y="Fund",
        orientation="h",
        color="Color",
        color_discrete_map={
            "Profit": "#16a34a",
            "Loss": "#dc2626",
        },
        hover_data={
            "Investment": ":,.2f",
            "Current Value": ":,.2f",
            "Profit/Loss": ":,.2f",
            "Return %": ":.2f",
        },
    )

    fig.update_layout(
        height=450,
        template="plotly_white",
        margin=dict(
            l=20,
            r=20,
            t=40,
            b=20,
        ),
        legend_title_text="",
        xaxis_title="Profit / Loss (₹)",
        yaxis_title="",
    )

    fig.update_traces(
        texttemplate="₹%{x:,.0f}",
        textposition="outside",
    )

    st.plotly_chart(
    fig,
    width="stretch",
    config={
        "displayModeBar": False,
    },
    key="analytics_gain_distribution_chart",
    )