"""add reconciliation exceptions

Revision ID: 0470048187cb
Revises: 2fa20e607d57
Create Date: 2026-07-24 23:43:03.779684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0470048187cb'
down_revision: Union[str, Sequence[str], None] = '2fa20e607d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_exceptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_item_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('exception_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('investigation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_item_id'], ['reconciliation_audit_items.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_exceptions_audit_item_id'), 'reconciliation_exceptions', ['audit_item_id'], unique=True)
    op.create_index(op.f('ix_reconciliation_exceptions_exception_type'), 'reconciliation_exceptions', ['exception_type'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_fund_id'), 'reconciliation_exceptions', ['fund_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_opened_at'), 'reconciliation_exceptions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_portfolio_id'), 'reconciliation_exceptions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_status'), 'reconciliation_exceptions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_exceptions_status'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_portfolio_id'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_opened_at'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_fund_id'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_exception_type'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_audit_item_id'), table_name='reconciliation_exceptions')
    op.drop_table('reconciliation_exceptions')
    # ### end Alembic commands ###
