"""add reconciliation audit tables

Revision ID: 2fa20e607d57
Revises: c33ae27092f3
Create Date: 2026-07-24 20:43:40.564901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa20e607d57'
down_revision: Union[str, Sequence[str], None] = 'c33ae27092f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_audit_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('unit_mismatch_count', sa.Integer(), nullable=False),
    sa.Column('missing_position_count', sa.Integer(), nullable=False),
    sa.Column('missing_tax_lot_count', sa.Integer(), nullable=False),
    sa.Column('cost_basis_variance_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_audit_snapshots_portfolio_id'), 'reconciliation_audit_snapshots', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_audit_snapshots_recorded_at'), 'reconciliation_audit_snapshots', ['recorded_at'], unique=False)
    op.create_table('reconciliation_audit_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('fund_name', sa.String(length=255), nullable=True),
    sa.Column('position_units', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('transaction_units', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unit_variance', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('position_cost_basis', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_cost_basis', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_basis_variance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['reconciliation_audit_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_audit_items_fund_id'), 'reconciliation_audit_items', ['fund_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_audit_items_snapshot_id'), 'reconciliation_audit_items', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_audit_items_status'), 'reconciliation_audit_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_audit_items_status'), table_name='reconciliation_audit_items')
    op.drop_index(op.f('ix_reconciliation_audit_items_snapshot_id'), table_name='reconciliation_audit_items')
    op.drop_index(op.f('ix_reconciliation_audit_items_fund_id'), table_name='reconciliation_audit_items')
    op.drop_table('reconciliation_audit_items')
    op.drop_index(op.f('ix_reconciliation_audit_snapshots_recorded_at'), table_name='reconciliation_audit_snapshots')
    op.drop_index(op.f('ix_reconciliation_audit_snapshots_portfolio_id'), table_name='reconciliation_audit_snapshots')
    op.drop_table('reconciliation_audit_snapshots')
    # ### end Alembic commands ###
