"""add reconciliation exception ownership

Revision ID: d4754e2f0752
Revises: 0470048187cb
Create Date: 2026-07-26 17:08:02.595372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4754e2f0752'
down_revision: Union[str, Sequence[str], None] = '0470048187cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_exception_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exception_id', sa.Integer(), nullable=False),
    sa.Column('previous_assigned_to', sa.String(length=255), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['reconciliation_exceptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_exception_assignments_assigned_at'), 'reconciliation_exception_assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_reconciliation_exception_assignments_assigned_to'), 'reconciliation_exception_assignments', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_reconciliation_exception_assignments_exception_id'), 'reconciliation_exception_assignments', ['exception_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_exception_assignments_previous_assigned_to'), 'reconciliation_exception_assignments', ['previous_assigned_to'], unique=False)
    op.add_column('reconciliation_exceptions', sa.Column('assigned_to', sa.String(length=255), nullable=True))
    op.add_column('reconciliation_exceptions', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_reconciliation_exceptions_assigned_to'), 'reconciliation_exceptions', ['assigned_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_exceptions_assigned_to'), table_name='reconciliation_exceptions')
    op.drop_column('reconciliation_exceptions', 'assigned_at')
    op.drop_column('reconciliation_exceptions', 'assigned_to')
    op.drop_index(op.f('ix_reconciliation_exception_assignments_previous_assigned_to'), table_name='reconciliation_exception_assignments')
    op.drop_index(op.f('ix_reconciliation_exception_assignments_exception_id'), table_name='reconciliation_exception_assignments')
    op.drop_index(op.f('ix_reconciliation_exception_assignments_assigned_to'), table_name='reconciliation_exception_assignments')
    op.drop_index(op.f('ix_reconciliation_exception_assignments_assigned_at'), table_name='reconciliation_exception_assignments')
    op.drop_table('reconciliation_exception_assignments')
    # ### end Alembic commands ###
