"""add reconciliation exception escalation

Revision ID: ed18209bf33b
Revises: d4754e2f0752
Create Date: 2026-07-26 19:59:45.325662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed18209bf33b'
down_revision: Union[str, Sequence[str], None] = 'd4754e2f0752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reconciliation_exceptions', sa.Column('priority', sa.String(length=32), server_default='normal', nullable=False))
    op.add_column('reconciliation_exceptions', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reconciliation_exceptions', sa.Column('escalation_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_reconciliation_exceptions_priority'), 'reconciliation_exceptions', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_exceptions_priority'), table_name='reconciliation_exceptions')
    op.drop_column('reconciliation_exceptions', 'escalation_reason')
    op.drop_column('reconciliation_exceptions', 'escalated_at')
    op.drop_column('reconciliation_exceptions', 'priority')
    # ### end Alembic commands ###
