"""
Portfolio performance analytics service.

This module calculates portfolio-level performance metrics from the
portfolio dataframe supplied by PortfolioService.

It does not load, mutate, or persist portfolio data.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final

import pandas as pd


@dataclass(frozen=True, slots=True)
class PortfolioPerformanceMetrics:
    """
    Immutable portfolio performance result.

    Attributes:
        total_investment:
            Total amount invested across all portfolio holdings.

        current_value:
            Current market value of the complete portfolio.

        total_gain:
            Difference between current value and total investment.

        absolute_return_percentage:
            Total portfolio return expressed as a percentage of the
            invested amount.

        profitable_holdings:
            Number of holdings with a positive gain.

        loss_making_holdings:
            Number of holdings with a negative gain.

        total_holdings:
            Number of holdings included in the calculation.
    """

    total_investment: float
    current_value: float
    total_gain: float
    absolute_return_percentage: float
    profitable_holdings: int
    loss_making_holdings: int
    total_holdings: int

    @property
    def is_profitable(self) -> bool:
        """Return True when the total portfolio gain is positive."""
        return self.total_gain > 0

    @property
    def is_at_loss(self) -> bool:
        """Return True when the total portfolio gain is negative."""
        return self.total_gain < 0


class PortfolioPerformanceService:
    """
    Calculate portfolio performance metrics.

    The service expects the portfolio dataframe generated by
    PortfolioService. It performs defensive validation before calculating
    portfolio metrics.
    """

    INVESTMENT_COLUMN: Final[str] = "Investment"
    CURRENT_VALUE_COLUMN: Final[str] = "Current Value"
    PROFIT_LOSS_COLUMN: Final[str] = "Profit/Loss"

    REQUIRED_COLUMNS: Final[tuple[str, ...]] = (
        INVESTMENT_COLUMN,
        CURRENT_VALUE_COLUMN,
    )

    def calculate(
        self,
        portfolio: pd.DataFrame,
    ) -> PortfolioPerformanceMetrics:
        """
        Calculate portfolio performance metrics.

        Args:
            portfolio:
                Portfolio dataframe returned by PortfolioService.

        Returns:
            PortfolioPerformanceMetrics containing portfolio-level
            performance calculations.

        Raises:
            TypeError:
                If portfolio is not a pandas DataFrame.

            ValueError:
                If the dataframe is empty, required columns are missing,
                or the required values cannot be converted to numbers.
        """
        self._validate_dataframe(portfolio)

        investment = self._get_numeric_series(
            portfolio=portfolio,
            column=self.INVESTMENT_COLUMN,
        )

        current_value = self._get_numeric_series(
            portfolio=portfolio,
            column=self.CURRENT_VALUE_COLUMN,
        )

        total_investment = float(investment.sum())
        total_current_value = float(current_value.sum())
        total_gain = total_current_value - total_investment

        absolute_return_percentage = self._calculate_absolute_return(
            total_investment=total_investment,
            total_gain=total_gain,
        )

        holding_gains = self._get_holding_gains(
            portfolio=portfolio,
            investment=investment,
            current_value=current_value,
        )

        profitable_holdings = int((holding_gains > 0).sum())
        loss_making_holdings = int((holding_gains < 0).sum())

        return PortfolioPerformanceMetrics(
            total_investment=total_investment,
            current_value=total_current_value,
            total_gain=total_gain,
            absolute_return_percentage=absolute_return_percentage,
            profitable_holdings=profitable_holdings,
            loss_making_holdings=loss_making_holdings,
            total_holdings=int(len(portfolio)),
        )

    def _validate_dataframe(self, portfolio: pd.DataFrame) -> None:
        """
        Validate the portfolio dataframe.

        Args:
            portfolio:
                Portfolio dataframe to validate.

        Raises:
            TypeError:
                If portfolio is not a pandas DataFrame.

            ValueError:
                If the dataframe is empty or required columns are missing.
        """
        if not isinstance(portfolio, pd.DataFrame):
            raise TypeError(
                "PortfolioPerformanceService requires a pandas DataFrame."
            )

        if portfolio.empty:
            raise ValueError(
                "Portfolio performance cannot be calculated because "
                "the portfolio dataframe is empty."
            )

        missing_columns = [
            column
            for column in self.REQUIRED_COLUMNS
            if column not in portfolio.columns
        ]

        if missing_columns:
            missing = ", ".join(missing_columns)

            raise ValueError(
                "Portfolio performance calculation requires the following "
                f"missing column(s): {missing}."
            )

    def _get_numeric_series(
        self,
        portfolio: pd.DataFrame,
        column: str,
    ) -> pd.Series:
        """
        Convert a portfolio column into a numeric series.

        Args:
            portfolio:
                Portfolio dataframe.

            column:
                Name of the column to convert.

        Returns:
            Numeric pandas Series with missing values replaced by zero.

        Raises:
            ValueError:
                If non-empty values cannot be converted to numbers.
        """
        original_series = portfolio[column]

        numeric_series = pd.to_numeric(
            original_series,
            errors="coerce",
        )

        invalid_mask = original_series.notna() & numeric_series.isna()

        if invalid_mask.any():
            invalid_count = int(invalid_mask.sum())

            raise ValueError(
                f"Column '{column}' contains {invalid_count} "
                "non-numeric value(s)."
            )

        return numeric_series.fillna(0.0).astype(float)

    def _get_holding_gains(
        self,
        portfolio: pd.DataFrame,
        investment: pd.Series,
        current_value: pd.Series,
    ) -> pd.Series:
        """
        Return gain or loss for each holding.

        The existing Profit/Loss column is used when available and valid.
        Otherwise, gains are calculated from Current Value minus Investment.

        Args:
            portfolio:
                Portfolio dataframe.

            investment:
                Numeric investment series.

            current_value:
                Numeric current-value series.

        Returns:
            Numeric pandas Series containing holding-level gains.
        """
        if self.PROFIT_LOSS_COLUMN not in portfolio.columns:
            return current_value - investment

        try:
            return self._get_numeric_series(
                portfolio=portfolio,
                column=self.PROFIT_LOSS_COLUMN,
            )
        except ValueError:
            # Analytics can still be calculated reliably from the two
            # authoritative valuation columns.
            return current_value - investment

    @staticmethod
    def _calculate_absolute_return(
        total_investment: float,
        total_gain: float,
    ) -> float:
        """
        Calculate absolute portfolio return percentage.

        Formula:
            Absolute Return = Total Gain / Total Investment * 100

        Args:
            total_investment:
                Total amount invested.

            total_gain:
                Current value minus invested amount.

        Returns:
            Absolute return percentage. Returns zero when investment is zero
            to prevent division-by-zero errors.
        """
        if total_investment == 0:
            return 0.0

        return float((total_gain / total_investment) * 100)